---
- name: Variables to install NFS server
  debug:
    msg:
    - "ansible_host = {{ ansible_host }}"
    - "ansible_hostname = {{ ansible_hostname }}"
    - "nfs_exports = {{ nfs_exports }}"
    - "nfs_export_dir_mode = {{ nfs_export_dir_mode }}"
    - "nfs_export_dir_owner = {{ nfs_export_dir_owner }}"
    - "nfs_export_dir_group = {{ nfs_export_dir_group }}"
    - "nfs_users_to_add_group = {{ nfs_users_to_add_group }}"
    - "nfs_users_to_add_group_by_uid = {{ nfs_users_to_add_group_by_uid }}"
    

- name: Install NFS required packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
      - acl
    state: present

- name: Ensure /etc/exports exists but do not touch timestamp
  copy:
    content: ""
    dest: /etc/exports
    force: no
    mode: '0644'

- name: Create default group for NFS users
  group:
    name: "{{ nfs_export_dir_group }}"
    state: present

- name: Add users to "{{ nfs_export_dir_group }}" group
  include_tasks: add_users_group.yml
  when: nfs_users_to_add_group | length > 0

- name: Add users to "{{ nfs_export_dir_group }}" group by UID
  include_tasks: add_users_group_by_uid.yml
  when: nfs_users_to_add_group_by_uid | length > 0

- name: Create NFS export volume directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.user | default(nfs_export_dir_owner) }}"
    group: "{{ item.group | default(nfs_export_dir_group) }}"
    mode: "{{ item.mode | default(nfs_export_dir_mode) }}"
    state: directory
  loop: "{{ nfs_exports }}"
  when: nfs_exports | length > 0
  notify: Restart NFS server

- name: Configure file /etc/exports
  lineinfile:
    dest: /etc/exports
    state: present
    line: "{% set default_opts = item.get('options', 'rw,sync,no_subtree_check,no_root_squash') -%} {% set raw_clients = item.get('clients', [{'cidr': '*', 'options': default_opts}]) -%} {% set clients_list = [] -%} {% if raw_clients is string -%} {%   set _ = clients_list.append({'cidr': raw_clients, 'options': default_opts}) -%} {% elif raw_clients is iterable -%} {%   for c in raw_clients -%} {%     if c is string -%} {%       set _ = clients_list.append({'cidr': c, 'options': default_opts}) -%} {%     else -%} {%       set _ = clients_list.append({'cidr': c.cidr, 'options': c.get('options', default_opts)}) -%} {%     endif -%} {%   endfor -%} {% endif -%} {{ item.path }} {{ clients_list | map(attribute='cidr') | zip(clients_list | map(attribute='options') | list) | map('join', '(') | map('regex_replace', '$', ')') | join(' ') }}"
  loop: "{{ nfs_exports }}"
  loop_control:
    label: "{{ item.path }}"
  when: nfs_exports | length > 0
  notify: Restart NFS server

- name: Configure ACLs and permissions for NFS export directories
  include_tasks: config_acl.yml
  when: nfs_exports | length > 0